2024-03-20 03:45:22,715 STDOUT INFO     Established redirection of `stdout`.
2024-03-20 03:45:22,715 pypet.storageservice.HDF5StorageService INFO     I will use the hdf5 file `hdf5\VariedTau\Main_TauVar.hdf5`.
2024-03-20 03:45:22,715 pypet.storageservice.HDF5StorageService INFO     You specified ``overwrite_file=True``, so I deleted the file `hdf5\VariedTau\Main_TauVar.hdf5`.
2024-03-20 03:45:22,715 pypet.environment.Environment INFO     Environment initialized.
2024-03-20 03:45:22,715 STDOUT INFO     Adding Parameters
2024-03-20 03:45:22,715 STDOUT INFO     Exploring across sig_s and sig_u
2024-03-20 03:45:22,715 STDOUT INFO     added exploration
2024-03-20 03:45:22,715 pypet.environment.Environment INFO     I am preparing the Trajectory for the experiment and initialise the store.
2024-03-20 03:45:22,715 pypet.environment.Environment INFO     Initialising the storage for the trajectory.
2024-03-20 03:45:22,715 pypet.storageservice.HDF5StorageService INFO     Initialising storage or updating meta data of Trajectory `dummy`.
2024-03-20 03:45:22,731 pypet.storageservice.HDF5StorageService INFO     Finished init or meta data update for `dummy`.
2024-03-20 03:45:22,746 pypet.environment.Environment INFO     
************************************************************
STARTING runs of trajectory
`dummy`.
************************************************************

2024-03-20 03:45:22,746 pypet.storageservice.HDF5StorageService INFO     Initialising storage or updating meta data of Trajectory `dummy`.
2024-03-20 03:45:22,762 pypet.storageservice.HDF5StorageService INFO     Finished init or meta data update for `dummy`.
2024-03-20 03:45:24,945 pypet.environment.MultiprocContext INFO     Starting the Storage Queue!
2024-03-20 03:45:25,024 pypet.environment.Environment INFO     Starting multiprocessing with at most 24 processes running at the same time.
2024-03-20 03:45:25,024 pypet INFO     PROGRESS: Finished 0/9 runs [                    ]  0.0%
2024-03-20 03:45:44,167 pypet INFO     PROGRESS: Finished 1/9 runs [==                  ] 11.1%, remaining: 0:02:33
2024-03-20 03:45:46,929 pypet INFO     PROGRESS: Finished 2/9 runs [====                ] 22.2%, remaining: 0:01:16
2024-03-20 03:45:46,992 pypet INFO     PROGRESS: Finished 3/9 runs [======              ] 33.3%, remaining: 0:00:43
2024-03-20 03:45:50,016 pypet INFO     PROGRESS: Finished 4/9 runs [========            ] 44.4%, remaining: 0:00:31
2024-03-20 03:45:52,213 pypet INFO     PROGRESS: Finished 5/9 runs [===========         ] 55.6%, remaining: 0:00:21
2024-03-20 03:45:54,642 pypet INFO     PROGRESS: Finished 6/9 runs [=============       ] 66.7%, remaining: 0:00:14
2024-03-20 03:45:56,600 pypet INFO     PROGRESS: Finished 7/9 runs [===============     ] 77.8%, remaining: 0:00:09
2024-03-20 03:45:59,020 pypet INFO     PROGRESS: Finished 8/9 runs [=================   ] 88.9%, remaining: 0:00:04
2024-03-20 03:46:01,016 pypet INFO     PROGRESS: Finished 9/9 runs [====================]100.0%
2024-03-20 03:46:01,362 pypet.environment.MultiprocContext INFO     The Storage Queue will no longer accept new data. Hang in there for a little while. There still might be some data in the queue that needs to be stored.
2024-03-20 03:46:01,566 pypet.environment.MultiprocContext INFO     The Storage Queue has joined.
2024-03-20 03:46:01,770 pypet.storageservice.HDF5StorageService INFO     Initialising storage or updating meta data of Trajectory `dummy`.
2024-03-20 03:46:01,786 pypet.storageservice.HDF5StorageService INFO     Finished init or meta data update for `dummy`.
2024-03-20 03:46:01,802 pypet.environment.Environment INFO     
************************************************************
FINISHED all runs of trajectory
`dummy`.
************************************************************

2024-03-20 03:46:01,802 pypet.environment.Environment INFO     
************************************************************
STARTING FINAL STORING of trajectory
`dummy`
************************************************************

2024-03-20 03:46:01,802 pypet.storageservice.HDF5StorageService INFO     Start storing Trajectory `dummy`.
2024-03-20 03:46:01,817 pypet.storageservice.HDF5StorageService INFO     Storing branch `config`.
2024-03-20 03:46:02,115 pypet.storageservice.HDF5StorageService INFO     Storing branch `parameters`.
2024-03-20 03:46:02,177 pypet.storageservice.HDF5StorageService INFO     Finished storing Trajectory `dummy`.
2024-03-20 03:46:02,177 pypet.environment.Environment INFO     
************************************************************
FINISHED FINAL STORING of trajectory
`dummy`.
************************************************************

2024-03-20 03:46:02,193 pypet.environment.Environment INFO     All runs of trajectory `dummy` were completed successfully.
2024-03-20 03:46:02,193 STDOUT INFO     Disabled redirection of `stdout`.
2024-03-20 03:46:02,193 pypet.storageservice.HDF5StorageService INFO     I will use the hdf5 file `hdf5\VariedTau\Main_TauVar.hdf5`.
2024-03-20 03:46:02,209 pypet.storageservice.HDF5StorageService INFO     Loading trajectory `dummy`.
2024-03-20 03:46:02,209 pypet.storageservice.HDF5StorageService INFO     Loading branch `config` in mode `2`.
2024-03-20 03:46:02,287 pypet.storageservice.HDF5StorageService INFO     Loading branch `parameters` in mode `2`.
2024-03-20 03:46:02,303 pypet.storageservice.HDF5StorageService INFO     Loading branch `results` in mode `2`.
2024-03-20 03:46:02,365 STDOUT INFO     Starting post proc
2024-03-20 03:46:02,381 pypet.storageservice.HDF5StorageService ERROR    Failed loading  `Trajectory dummy (`Setting up the pypet pipeline for our temporal model of character displacement. `, len:9): (config: <class 'pypet.naturalnaming.ConfigGroup'>), (parameters: <class 'pypet.naturalnaming.ParameterGroup'>), (results: <class 'pypet.naturalnaming.ResultGroup'>)`
2024-03-20 03:46:02,381 pypet.naturalnaming.NaturalNamingInterface ERROR    Error while auto-loading `tau1` under ``.
2024-03-23 15:32:02,011 Comm ERROR    Exception in comm_msg for 70762c2de63511ee879bbe9ad736c474
Traceback (most recent call last):
  File "C:\Users\laksh\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 347, in _handle_remote_call
    self._set_call_return_value(msg_dict, return_value)
  File "C:\Users\laksh\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 384, in _set_call_return_value
    self._send_message('remote_call_reply', content=content, data=data,
  File "C:\Users\laksh\anaconda3\lib\site-packages\spyder_kernels\comms\frontendcomm.py", line 109, in _send_message
    return super(FrontendComm, self)._send_message(*args, **kwargs)
  File "C:\Users\laksh\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 238, in _send_message
    raise CommError("The comm is not connected.")
spyder_kernels.comms.commbase.CommError: The comm is not connected.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\laksh\anaconda3\lib\site-packages\comm\base_comm.py", line 263, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\laksh\anaconda3\lib\site-packages\spyder_kernels\comms\frontendcomm.py", line 256, in handle_msg
    comm._msg_callback(msg)
  File "C:\Users\laksh\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 333, in _comm_message
    self._message_handlers[spyder_msg_type](
  File "C:\Users\laksh\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 351, in _handle_remote_call
    self._set_call_return_value(msg_dict, exc_infos, is_error=True)
  File "C:\Users\laksh\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 384, in _set_call_return_value
    self._send_message('remote_call_reply', content=content, data=data,
  File "C:\Users\laksh\anaconda3\lib\site-packages\spyder_kernels\comms\frontendcomm.py", line 109, in _send_message
    return super(FrontendComm, self)._send_message(*args, **kwargs)
  File "C:\Users\laksh\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 238, in _send_message
    raise CommError("The comm is not connected.")
spyder_kernels.comms.commbase.CommError: The comm is not connected.
